services:
  - type: web
    name: waqtmoney-api
    runtime: node
    rootDir: Server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_BASE_URL
        value: https://waqtmoney.com
      - key: API_PUBLIC_BASE_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: APP_SECRET_KEY
        sync: false
      - key: BIFROST_API_TOKEN
        sync: false
      - key: BIFROST_REACT_API_TOKEN
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_SECURE
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
